name: Deploy via ftp
on: push: branches: [ master ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.ftp_server }} 
        user: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        localDir: "."
        remoteDir: "public_html"
        forceSsl: false